version: '2'
services:
  eureka-server-1:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-2-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-1
    ports:
      - "8761:8080"
    environment:
      - JAVA_OPTS=-server -Xmx1g
      - SERVER_PORT=8080
      - CONFIG_SERVER_HOST=192.168.179.117
      - CONFIG_SERVER_PORT=8888
      - EUREKA_SERVER_HOST=192.168.179.117
      - EUREKA_SERVER_PORT=8762
    depends_on:
      - config-server
    volumes:
    - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: /wait-for-it.sh -d  config-server:3306 -c 'echo "start eureka-server-2 service here"'
  eureka-server-2:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-2-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-2
    ports:
    - "8762:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - SERVER_PORT=8080
    - CONFIG_SERVER_HOST=192.168.179.117
    - CONFIG_SERVER_PORT=8888
    - EUREKA_SERVER_HOST=192.168.179.117
    - EUREKA_SERVER_PORT=8761
    depends_on:
    - config-server
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: /wait-for-it.sh -d  config-server:3306 -c 'echo "start eureka-server-2 service here"'
  config-server:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-1-config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
    - "8888:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - PROFILE=jdbc
    - SERVER_PORT=8080