version: '3'
services:
  eureka-server-1:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-2-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-1
    ports:
      - "8761:8080"
    environment:
      - JAVA_OPTS=-server -Xmx1g
      - SERVER_PORT=8080
      - CONFIG_SERVER_HOST=192.168.179.117
      - CONFIG_SERVER_PORT=8888
      - EUREKA_SERVER_HOST=192.168.179.117
      - EUREKA_SERVER_PORT=8762
    depends_on:
      - config-server
    restart: on-failure
  eureka-server-2:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-2-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server-2
    ports:
    - "8762:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - SERVER_PORT=8080
    - CONFIG_SERVER_HOST=192.168.179.117
    - CONFIG_SERVER_PORT=8888
    - EUREKA_SERVER_HOST=192.168.179.117
    - EUREKA_SERVER_PORT=8761
    depends_on:
    - config-server
    restart: on-failure
  gateway-server:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-3-gateway:0.0.1-SNAPSHOT
    container_name: gateway-server
    ports:
    - "8000:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - SERVER_PORT=8080
    - CONFIG_SERVER_HOST=192.168.179.117
    - CONFIG_SERVER_PORT=8888
    - EUREKA_SERVER_HOST=192.168.179.117
    - EUREKA_SERVER_PORT=8761
    depends_on:
    - config-server
    restart: on-failure
  biz-server:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-6-biz-service:0.0.1-SNAPSHOT
    container_name: biz-server
    ports:
    - "8003:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - SERVER_PORT=8080
    - CONFIG_SERVER_HOST=192.168.179.117
    - CONFIG_SERVER_PORT=8888
    - EUREKA_SERVER_HOST=192.168.179.117
    - EUREKA_SERVER_PORT=8761
    depends_on:
    - config-server
    restart: on-failure
  config-server:
    image: registry.cn-hangzhou.aliyuncs.com/springcloud-cn/ch22-2-1-config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
    - "8888:8080"
    environment:
    - JAVA_OPTS=-server -Xmx1g
    - PROFILE=jdbc
    - SERVER_PORT=8080
