spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 与服务发现组件组合，进行路由
          lowerCaseServiceId: true # 默认使用服务名大写路由，改配置为服务名写

server:
  port: 9000  #网关服务监听 9000 端口
eureka:
  client:
    service-url: #指定注册中心的地址，以便使用服务发现功能
      defaultZone: http://localhost:8761/eureka/

logging:
  level: #调整相关包的 log 级别，以便排查问题
    org.springframework.cloud.gateway: debug


#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:
      exposure:
        include: "*"