server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:  # http://localhost:8080/actuator/gateway/routes
      exposure:
        include: "*"

# 等价说代码中的写法
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: after_route
#        uri: http://baidu.com
#        predicates:
#        - After=2018-11-08T14:57:34.443+08:00[Asia/Shanghai]